@Library('demoSharedLibrary') _
pipelineTemplate(
    appName: "Bank App",
    buildCommand: "mvn clean install",
    testCommand: "mvn test",
    sonarCommand: "mvn sonar:sonar",
    deploy: true,
    deployCommand: "echo deploy"
)